services:
  db:
    image: postgres:13
    container_name: sample_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env.db

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    restart: unless-stopped
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - "9187:9187"
    depends_on:
      - db