services:
  app:
    image: ghcr.io/humanbojack/sample_app:latest
    container_name: sample_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.app

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    restart: unless-stopped
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock