services:
  app:
    image: ghcr.io/humanbojack/sample_app:latest
    container_name: sample_app
    restart: unless-stopped
    env_file:
      - .env.app
    depends_on:
      db:
        condition: service_started
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: sample_db
    restart: unless-stopped
    env_file:
      - .env.db