services:
  app:
    image: ghcr.io/humanbojack/sample_app:latest
    container_name: sample_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.app

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock